### ISSUE TITLE
Issue 5: for Milestone 3: Training the Model (Lab 5 - 8)

### ISSUE THREAD

**Issue by Mchllar** [Mchllar/WaridiPastries#5]
- [x] Data splitting
- [x] Bootstrapping
- [x] Cross validation (basic, repeated, or LOOCV)
- [x] Model training either classification, regression, association, or clustering (as applicable)
- [x] Model performance comparison using resampling (for classification and regression)

**Comment by Mchllar** [comment]
Bootstrapping was not applicable since the dataset was large enough.
